apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:A8NPV7C5NRj8yNVj2Vv1PTkodBY=,iv:TR43NbFhvLdwX8YXx1BBchusonDOULQwn7CclbJ+JUw=,tag:D3TLYfljC0KOk+fgmfRn3g==,type:str]
    admin-user: ENC[AES256_GCM,data:UOWl4gPwT9YkqQCt,iv:W+e0m4K6YIIbHSxUT6AN3Qpn6cB/2froSh6yvSy6gks=,tag:E5mowaDtbNVblZxefv0PwA==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MzMvK0R5MnhBeWE4L09J
            U3ZMK0pLajNpOGorYjJOeEFzY2ZFN1J4UFRZCmljWDhLWHFmcjEwUmpUbk5LK2Vm
            VWNnWHkzdUJnNUJpTGN0Q2tlTmE2OHcKLS0tIHBoZmQvZmQzRnJyV0w5S2g2ZVFq
            U0hNSjRzNS92Nmx2QXhhdHVHUkZDejQKg/EshiUbfYsQau+tfcBBsXcGlg6hTql6
            Jmju8yd1HaOib0DHIB5q34R7efgGWrtkx4/omS9f0y2CHxoxArosbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aq9stltdq5m9x4xcdnjdlg0jaw5udw55qhxn4rnecclfssmtaqys89un53
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T07:14:57Z"
    mac: ENC[AES256_GCM,data:pNWoNtdhSNrgYElgKyfuT3rJ4wynH2uLChtfo5DORVJ4HzziVhIljjv0R06diaIH+kXWegvNlKYF76f3Ew+bdHZufiSe/JpvVYgRMPLC7WoTXYGB05Skl4NYVFaLRY2WDc54ffPFcQdlArfIbSw11CF5f13MlIAtuu5V7WuPav0=,iv:0pxecW4Df1o+3F/UCA3OQKozaQoji/pJ63bgjAW6wiw=,tag:1si8TFu4bJ/eogBdrQWTLQ==,type:str]
    version: 3.13.3
