apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:/ECcg812yHAO5ns4n2Tjp1KlKr6jtnbuqq9uOSWrpcGSofO+pwFetzxm+/KUzOmc/lDug+7W9RGqtp5AM72bTG063rz+SvijqUC0oE33IEjGlZ4qQ5dB6wVw15MNHnnk+U0ShukfNDU3DvrfE6hU3GtwFdilpTCnWvKEK3TM00RSVn9ZZjRHu4k2BAzUHzfoiSsi/gMXDhEuQ/p43BJ1inicClrK7l0hVTmGXuRqn+8VF0UpZnfiRuKfAYrTLtJ3pDz/7TpU8fhnJ5jgY0IlsYtzdyRV3mLox5/XZJJ/aJU/gDM/Z96jZsogjx8=,iv:RdXidpwyfURTyh4APzTI4Wx0es25KPoWsXQ+2nSbBvE=,tag:/7QkvvXm+28qhV05PWnE9A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaFNXeHVDaFlpSjFJcjRx
            a3ZGZkl5MHZ5V0NlTi9GNjA1NHZlTDlHTkRnClJOakhha2FGVFBKN2hhSUdmMEdz
            UDY4dGorTmFzL0UyMlVPNnBvNGlvWEkKLS0tIG9tbGYzT2w3cU9CN0JZV1hmWTRC
            dzE0b2s0VjUvZ2hXM2s2RjlTZTRpVVkKYwZVup87mUQkX/ds4cc8QOQ5HVZ2TRxQ
            IexZ3Dq+vQALl1OCdPLVcR/fy+qVlCWgsKRPzVYw7yvVrIgRQzByLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aq9stltdq5m9x4xcdnjdlg0jaw5udw55qhxn4rnecclfssmtaqys89un53
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T09:10:47Z"
    mac: ENC[AES256_GCM,data:yA3h3gHrQ1dH8u13B0Yg2J6c5RWHYlb9oO7X84vtwQE8AygIonBMeEtPM7iYkfNDyWUvRCog2qSriAiRgWgrxUuC4iZldVVfRQvwjVBruhd5uWlVlAFx8THKAbHshFQAKLlMGcsTR8ku/omr0RutrVffgPH8WO2bDEyEXnjM0Us=,iv:/Vn2x1Kr9lpwlFEWc2KEtrmJR1F8xuZqKUcTTJF3vC4=,tag:m2Ua8loNiOQjgi5LypgjYg==,type:str]
    version: 3.13.3
