apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:E92HMqUtVVZHJrmf,iv:9BpiyygYE5tl/3cyxXqFs5hXLULut0FWFL5qZY7353c=,tag:/X+lgK8UKvJZPZfd+Y7XQw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:H9HZd8Px4zz0fSUhUPhcTA==,iv:kNaVJNtPfpQQiSkOupqupOpB0O0FLQ1+zHQumMb2mpQ=,tag:DuImxf90y5Km5xvU2pIdVw==,type:str]
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycGpHLzAybWVyMlE1WDlz
            eVN2SHBUcDB5UkRLZU85WnpqUU1yUWR3aVVnCks4NGk3YnZnbmdZbExTZWRMdEov
            K2dpRUVralRVZVhITlB6ZkpzTEhRdHcKLS0tIEZFejl2OE9CRldhclBFZHRxYlAw
            UHI2c1MyU0l3RTRycHNXdnJ1R09GWFkKJJzPRFG2pWc+mRLrj7dYelsZ5oSTWDQ8
            Y65LB/XePT2HBPsv15iDf4vq/cdaOzC5/ImBhpSry+d7VDIlL7G4og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aq9stltdq5m9x4xcdnjdlg0jaw5udw55qhxn4rnecclfssmtaqys89un53
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T04:05:11Z"
    mac: ENC[AES256_GCM,data:J+qyXcs+SwvV2pN1FSNVY/hwNmnMp/1iqsR6rROvlMaNqkmH5VWJA/uq92oN810Ok9aQ4rtDvDcpy+PGvECOQrl+/8kqhSTD2YblXjmnf1C/VeT7G7fI3o3V6RcOKa3ZRB+gxf/I8uuemv1HjlJ6zivBklD9C/JHQjI+cxd/Er0=,iv:ictCmKQWfmXr/cERL5CMICIjApxQ9S3bXXyRzNBjDr4=,tag:+SlfPDFboZbKzpvg4cn+rw==,type:str]
    version: 3.13.3
